[package]
name = "dgb-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = "1"
serde_derive = "1"
serde_json = "1"
url_encoded_data = "0.6"
sublime_fuzzy = "0.7.0"
lazy_static = "1.4.0"
regex = "1.5.5"
