apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: DOCKER_CONFIG_JSON
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
type: Opaque
stringData:
  api-token: API_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: root-access
type: Opaque
stringData:
  email: ROOT_EMAIL
  passwort: HTTPS_ARGON2_DOT_ONLINE
  smtp-host: ""
  smtp-passwort: ""
  smtp-email: ""
