apiVersion: v1
kind: Secret
metadata:
  name: acme-config
type: Opaque
stringData:
  domains: "grundbuch-test.eu, test.grundbuch-test.eu",
  email: "abc@test.com",
  cache: /tmp/cache/acme_challenges,
  prod: true,
