name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+*" ]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
          description: 'Make release'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/dgb-server:latest
    - name: docker login
      if: github.event.inputs.release != ''
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}
    - name: tag latest image
      if: github.event.inputs.release != ''
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/dgb-server:latest ${{ secrets.DOCKER_USERNAME }}/dgb-server:${{ github.event.inputs.release }}
    - name: docker push
      if: github.event.inputs.release != ''
      run: docker push ${{ secrets.DOCKER_USERNAME }}/dgb-server:${{ github.event.inputs.release }}
